### ISSUE TITLE
Not proper syntax

### ISSUE THREAD

**Issue by DanielRivasMD** [JuliaDebug/Debugger.jl#274]
This is such an awesome tool. However, everytime that I try to use in a complex function (several lines of code, calling other functions or other elements) the synthax goes weird looking like low level code. Not entirely certain what could be the issue

**Comment by KristofferC** [comment]
It could be that it fails to look up the source code. If you have an example when this happens we can try to fix it. Also, make sure you are on the latest versions of everything, specifically 1.0.3 of CodeTracking.jl because some bugs with this have been fixed.

**Comment by DanielRivasMD** [comment]
Thanks for your response. I do have the latest versions of the packages (just checked). Here is the function I was working on now, but this has happened on other similar situations:

`function extractChannelSignalBin(channel; binSize = 256, binOverlap = 8)
  # define variables
  stepSize = floor(Int32, binSize / binOverlap)
  signalSteps = 1:stepSize:(channel |> length)
  signalAr = Array{Float64}(undef, (signalSteps |> length), binSize)

  # iterate over signal bins
  for stepIx in 1:(signalSteps |> length)
    signalBoundry = signalSteps[stepIx] + binSize - 1
    # adjust last bin
    if signalBoundry > (channel |> length)
      signalBoundry = (channel |> length)
    end

    # extract signals
    signalAr[stepIx, :] = channel[signalSteps[stepIx]:signalBoundry]
  end
  return signalAr
end
`

When I enter debug mode where `ch` is just an array of integers:

`julia> @enter x = extractChannelSignalBin(ch)
In ##thunk#374() at REPL[112]:1
>1  1 ─ %1 = (extractChannelSignalBin)(Main.ch)
 2  │        x = %1
 3  └──      return %1

About to run: <(extractChannelSignalBin)(Int16[-227, -367, -224, -352, -249, -140, -126, -72, -141, -214, -200, -144...>
1|debug>`

I tried to use debugger on simpler functions, such as calculating the square of an integer, and it works fine.

**Comment by KristofferC** [comment]
I put your function in `file.jl` and it seems to work fine for me:

```
julia> using Debugger

julia> include("file.jl")
extractChannelSignalBin (generic function with 1 method)

julia> @enter x = extractChannelSignalBin(rand(Int, 5))
In ##thunk#254() at REPL[7]:1
>1  @enter x = extractChannelSignalBin(rand(Int, 5)

About to run: (rand)(Int64, 5)
1|debug> se
In ##thunk#254() at REPL[7]:1
>1  @enter x = extractChannelSignalBin(rand(Int, 5)

About to run: <(extractChannelSignalBin)([-1349184094340749919, 755358142409396267, 2071403546006836726, -6111912452...>
1|debug> s
In #extractChannelSignalBin#2(binSize, binOverlap, , channel) at /home/kc/JuliaTests/file.jl:1
 1  function extractChannelSignalBin(channel; binSize = 256, binOverlap = 8)
 2    # define variables
>3    stepSize = floor(Int32, binSize / binOverlap)
 4    signalSteps = 1:stepSize:(channel |> length)
 5    signalAr = Array{Float64}(undef, (signalSteps |> length), binSize)
 6
 7    # iterate over signal bins

About to run: (/)(256, 8)
```

**Comment by DanielRivasMD** [comment]
That is extremly odd. I started a fresh session with no other packages loaded and what you entered exactly. Still get the same result

**Comment by pfitzseb** [comment]
What Julia version are you on?

**Comment by DanielRivasMD** [comment]
julia version 1.5.2

**Comment by DanielRivasMD** [comment]
So it seems that `Debugger` got stuck on lower code. Typing `L` does not return the proper syntax.

**Comment by KristofferC** [comment]
If it can't find the source files it prints lowered code instead. So for some reason, it can't find it on your machine.

**Comment by DanielRivasMD** [comment]
Where should it be located? I am on OSX

**Comment by timholy** [comment]
It's hard to debug this remotely, so we might need you to poke at this a bit locally. The code to find your source file comes from [CodeTracking](https://github.com/timholy/CodeTracking.jl), so you could test it directly and report back. Debugger's use of CodeTracking is encapsulated in https://github.com/JuliaDebug/Debugger.jl/blob/7a2b9633936bb4a9033a452263b76982ca346d62/src/locationinfo.jl#L1-L25

You should also try with and without Revise loaded (before you load the source file you're trying to debug), and let us know which things fail under which conditions. (Most things work better in debugging if you're using Revise.)

**Comment by KristofferC** [comment]
Need more info here to do anything.

**Comment by DanielRivasMD** [comment]
Well, I tried last comment, but could not figure out how to make it work. Not certain what other information you would require.
